import { invariant } from '../../core/index.js';

// Noms communs français courants, en majuscules et sans accents (3 à 8 lettres), pour les grilles de mots croisés.
const RAW = `
ARBRE ETOILE SOLEIL LUNE TERRE MER RIVIERE ROUTE PORTE TABLE CHAISE LIVRE CARTE PIERRE SABLE NUAGE PLUIE NEIGE VENT
ORAGE FLEUR ROSE TULIPE LILAS SAPIN CHENE PALMIER RAISIN POIRE POMME CERISE CITRON ORANGE MELON OLIVE TOMATE SALADE
RADIS NAVET CAROTTE PAIN SEL SUCRE MIEL LAIT BEURRE CREME TARTE GATEAU CAFE THE SIROP SAUCE PATES RIZ SOUPE CHAT
CHIEN LAPIN LION TIGRE OURS LOUP RENARD CERF ANE CHEVAL MOUTON TAUREAU SINGE RAT SOURIS OISEAU AIGLE CANARD OIE
POULE COQ DINDE MERLE PIE CYGNE ZEBRE GIRAFE KOALA PANDA LEZARD SERPENT TRUITE SAUMON THON SARDINE CRABE HOMARD
MOULE HUITRE BALEINE REQUIN DAUPHIN PHOQUE STYLO CRAYON GOMME REGLE CAHIER SAC VALISE CLE LAMPE BOUGIE MIROIR TAPIS
RIDEAU LIT DRAP OREILLER COUSSIN CANAPE ARMOIRE TIROIR PLACARD FENETRE TOIT MUR SOL ESCALIER CAVE GRENIER JARDIN
PARC BANC FONTAINE STATUE MUSEE THEATRE CINEMA ECOLE LYCEE USINE BUREAU GARE TRAIN AVION BATEAU VOILE RAME PORT
PLAGE DUNE FALAISE ILE LAC ETANG SOURCE GLACIER MONT COLLINE VALLEE PLAINE FORET BOIS PRE CHAMP FERME GRANGE MOULIN
PONT TOUR CHATEAU PALAIS EGLISE TEMPLE VILLE VILLAGE RUE AVENUE PLACE MARCHE SALON CUISINE ASSIETTE TASSE VERRE
BOL POELE FOUR EVIER SAVON PEIGNE BROSSE PARFUM ROBE JUPE PULL VESTE MANTEAU CHEMISE BOTTE SANDALE CHAPEAU BONNET
GANT ECHARPE CEINTURE BAGUE COLLIER MONTRE AMOUR AMITIE JOIE RIRE REVE ESPOIR PAIX GLOIRE TALENT SUCCES ESPRIT
SAGESSE COURAGE FORCE AUDACE VICTOIRE TRESOR FORTUNE CHANCE DESTIN ETE HIVER AUTOMNE SAISON MATIN SOIR NUIT MIDI
SEMAINE ANNEE SIECLE HEURE MINUTE SECONDE PIANO GUITARE VIOLON FLUTE TAMBOUR HARPE CHANSON OPERA DANSE BALLET
TENNIS RUGBY JUDO BOXE GOLF SKI VELO COURSE SPRINT RELAIS BUT BALLE BALLON RAQUETTE FILET PISTE STADE ARENE
KIWI KILO KAYAK JOKER KIOSQUE WAGON WEEKEND WAPITI TRAMWAY BOWLING WHISKY ZERO ZONE ZOO JAZZ PIZZA GAZ NEZ ZINC
QUIZ QUAI QUILLE QUEUE CINQ TOQUE LAQUE MASQUE RISQUE BASQUE PLAQUE BARQUE CASQUE DISQUE BOUQUET PAQUET QUARTZ
TAXI LUXE TEXTE EXIL YEUX YOGA YAOURT YACHT LYNX JEU JOUR JAUNE JUMEAU JAMBE JOUET JUS JETON HIBOU HERBE HOTEL
HUILE HACHE HAMAC HARICOT HUMOUR HABIT HALTE HAMEAU HORLOGE FUMEE FROMAGE FRAISE FORGE FUSEE FLAMME FAKIR GIVRE
GLACE GRELE GALET GRAIN GUIDE BIJOU BULLE BRUME BOCAL BOUCLE BUFFET BISON VIGNE VOLCAN VALSE VELOURS VOYAGE VIRAGE
VITESSE VAPEUR MOTEUR PNEU VOLANT PILOTE CIRCUIT PODIUM COUPE DRAPEAU TURBO RALLYE GARAGE ESSENCE BOLIDE CHRONO
ATELIER ANCRE ARGENT ASTRE ATOUT AUBE AVENIR BAIN BARON BASSIN BETON BIDON BILLE BOUTON CABANE CADRE CALME CANAL
CANON CAPE CASERNE CERCLE CIEL CIRQUE CLOCHE CLOWN COEUR COIN COL COLIS COMETE CONTE CORDE COTE COUTEAU CRIQUET
CUIVRE DALLE DENT DESERT DIAMANT DOIGT DOMINO DOUANE DRAGON ECLAIR ECRAN EPEE EPICE ETAGE FARINE FEE FENOUIL FESTIN
FIL FLOCON FOIRE FOSSE FRERE FRONT FRUIT GAMIN GENOU GLAND GORGE GOUTTE GRAVIER GRILLE GROTTE GUEPE HALLE HERON
INDICE ISLE JAVELOT LAINE LARME LATTE LAURIER LEGUME LETTRE LIANE LIERRE LIMACE LINGE LITRE LOTO LUTIN MAGIE
MAIRIE MAISON MARIN MARRON MATELAS MELODIE MENU METAL METRO MINE MOINE MONDE MORSE MOTTE MOUCHE MUSIQUE NAPPE
NECTAR NID NOTE NOUGAT OCEAN ODEUR OEUF OMBRE ONCLE OPALE ORDRE ORTIE OUTIL PAGE PAILLE PANIER PAPIER PARADE
PASTEL PATTE PEINTRE PELLE PERLE PETALE PIED PILE PINCEAU PIPE PIRATE PLUME POCHE POESIE POISSON POIVRE POMPE
PRAIRIE PRINCE PRUNE PUITS PUZZLE RACINE RADIO RAMEAU RAYON RECOLTE REINE RENNE RESEAU RIVAGE ROBOT ROCHER ROI
ROMAN RONDE ROSEAU ROUE RUBAN RUCHE SAFRAN SALLE SALUT SENTIER SIRENE SOLDAT SOMMET SONNET SORCIER STAR SUD TAMIS
TANTE TAUPE TENTE TIGE TISANE TITRE TOILE TOMATE TORRENT TORTUE TRACTEUR TRAIT TRIO TROMPE TUNNEL TUILE UNIVERS
USAGE VACHE VAGUE VALET VASE VELIN VENIN VERGER VERNIS VIANDE VIDEO VINAIGRE VIRUS VITRE VITRAIL VOISIN VOLET
`;

export const FRENCH_WORDS: readonly string[] = [...new Set(RAW.trim().split(/\s+/))];

invariant(
  FRENCH_WORDS.every((word) => /^[A-Z]{3,8}$/.test(word)),
  'Dictionnaire de mots croisés : mots de 3 à 8 lettres majuscules sans accent attendus',
);
